# Generated by Django 4.2.16 on 2024-10-20 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='card',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='label',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
