# Generated by Django 4.2.16 on 2024-10-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_card_updated_at_card_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
